# Generated by Django 5.1.15 on 2026-09-24 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='نام پروژه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('planned', 'planned'), ('active', 'active'), ('blocked', 'blocked'), ('testing', 'testing'), ('bug_fixing', 'bug_fixing'), ('done', 'done'), ('paused', 'paused'), ('cancelled', 'cancelled')], db_index=True, default='planned', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], db_index=True, default='medium', max_length=20, verbose_name='اولویت')),
                ('risk_status', models.CharField(choices=[('on_track', 'on_track'), ('at_risk', 'at_risk'), ('blocked', 'blocked')], db_index=True, default='on_track', max_length=20, verbose_name='وضعیت ریسک')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('expected_completion', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام مورد انتظار')),
                ('actual_completion', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام واقعی')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='کلاینت/دستگاه درخواست\u200cکننده')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='teams.member', verbose_name='مالک/مدبر پروژه')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead', models.BooleanField(default=False, verbose_name='مسئول پروژه')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='teams.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='projects.project')),
            ],
            options={
                'verbose_name': 'عضو پروژه',
                'verbose_name_plural': 'اعضای پروژه',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectMember', to='teams.member', verbose_name='اعضا'),
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=30, verbose_name='فیلد')),
                ('old_value', models.CharField(blank=True, max_length=200, verbose_name='مقدار قبل')),
                ('new_value', models.CharField(blank=True, max_length=200, verbose_name='مقدار بعد')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییردهنده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='projects.project')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت پروژه',
                'verbose_name_plural': 'تاریخچه وضعیت پروژه',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['member', 'project'], name='projects_pr_member__a75dc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'member')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', 'status'], name='projects_pr_team_id_4a0091_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', 'priority'], name='projects_pr_team_id_468b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstatushistory',
            index=models.Index(fields=['project', '-created_at'], name='projects_pr_project_7ebe83_idx'),
        ),
    ]
