# Generated by Django 5.1.15 on 2026-09-24 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('project_created', 'project created'), ('project_updated', 'project updated'), ('project_status_changed', 'project status changed'), ('priority_changed', 'priority changed'), ('expected_completion_changed', 'expected completion changed'), ('member_assigned', 'member assigned'), ('member_removed', 'member removed'), ('task_created', 'task created'), ('task_status_changed', 'task status changed'), ('task_assigned', 'task assigned'), ('blocker_created', 'blocker created'), ('blocker_resolved', 'blocker resolved'), ('support_created', 'support ticket created'), ('support_status_changed', 'support status changed'), ('capacity_updated', 'capacity updated'), ('incoming_work_created', 'incoming work created'), ('incoming_work_converted', 'incoming work converted'), ('member_role_changed', 'member role changed')], db_index=True, max_length=50, verbose_name='action')),
                ('actor_name', models.CharField(blank=True, max_length=200, verbose_name='executor name')),
                ('entity_type', models.CharField(db_index=True, max_length=50, verbose_name='entity type')),
                ('entity_id', models.CharField(max_length=64, verbose_name='entity ID')),
                ('entity_label', models.CharField(blank=True, max_length=300, verbose_name='entity title')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='old value')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='new value')),
                ('note', models.TextField(blank=True, verbose_name='notes')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='executor')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='teams.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'change record',
                'verbose_name_plural': 'change records',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriorityChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_priority', models.CharField(max_length=20, verbose_name='old priority')),
                ('new_priority', models.CharField(max_length=20, verbose_name='new priority')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('impact', models.TextField(blank=True, verbose_name='impact')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_changes', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'priority change',
                'verbose_name_plural': 'priority changes',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='audit_prior_project_5bed24_idx')],
            },
        ),
    ]
