# Generated by Django 5.1.15 on 2026-09-24 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('support', '0001_initial'),
        ('teams', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='منبع/درخواست\u200cکننده')),
                ('status', models.CharField(choices=[('new', 'new'), ('evaluating', 'evaluating'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('converted_task', 'converted_task'), ('converted_support', 'converted_support'), ('converted_project', 'converted_project')], db_index=True, default='new', max_length=30, verbose_name='وضعیت')),
                ('converted_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_conversions', to='projects.project', verbose_name='پروژه هدف')),
                ('converted_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_conversions', to='support.supportticket', verbose_name='تیکت هدف')),
                ('converted_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_conversions', to='work.task', verbose_name='وظیفه هدف')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_work', to='teams.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'کار ورودی',
                'verbose_name_plural': 'کارهای ورودی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'status'], name='incoming_in_team_id_e331e6_idx')],
            },
        ),
    ]
