# Generated by Django 5.1.15 on 2026-09-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('todo', 'todo'), ('in_progress', 'in_progress'), ('blocked', 'blocked'), ('done', 'done')], db_index=True, default='todo', max_length=20, verbose_name='وضعیت')),
                ('work_type', models.CharField(choices=[('feature', 'feature'), ('bug', 'bug'), ('support', 'support'), ('change_request', 'change_request'), ('emergency', 'emergency')], default='feature', max_length=30, verbose_name='نوع کار')),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], default='medium', max_length=20, verbose_name='اولویت')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تکمیل')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('blocked', models.BooleanField(default=False, verbose_name='مسدود')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='teams.member', verbose_name='مسئول')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='teams.member', verbose_name='ایجادکننده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='work_task_project_23e8b8_idx'), models.Index(fields=['assignee', 'status'], name='work_task_assigne_fa6022_idx')],
            },
        ),
    ]
