# Generated by Django 5.1.15 on 2026-09-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percent', models.PositiveIntegerField(default=10, verbose_name='درصد')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='teams.member', verbose_name='عضو')),
                ('project', models.ForeignKey(blank=True, help_text='برای سهم «پشتیبانی» خالی بگذارید.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تخصیص ظرفیت',
                'verbose_name_plural': 'تخصیص\u200cهای ظرفیت',
                'ordering': ['member', '-percent'],
                'unique_together': {('member', 'project')},
            },
        ),
    ]
