# Generated by Django 5.1.15 on 2026-09-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('requester', models.CharField(blank=True, max_length=200, verbose_name='درخواست\u200cدهنده')),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], default='medium', max_length=20, verbose_name='شدت')),
                ('status', models.CharField(choices=[('new', 'new'), ('assigned', 'assigned'), ('in_progress', 'in_progress'), ('waiting', 'waiting'), ('resolved', 'resolved'), ('closed', 'closed')], db_index=True, default='new', max_length=20, verbose_name='وضعیت')),
                ('work_type', models.CharField(choices=[('feature', 'feature'), ('bug', 'bug'), ('support', 'support'), ('change_request', 'change_request'), ('emergency', 'emergency')], default='support', max_length=30, verbose_name='نوع کار')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='حل\u200cشدن')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='teams.member', verbose_name='توسعه\u200cدهنده مسئول')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='support_sup_status_52a4ed_idx'), models.Index(fields=['assignee', 'status'], name='support_sup_assigne_1ad203_idx'), models.Index(fields=['project', 'status'], name='support_sup_project_81abf0_idx')],
            },
        ),
    ]
