# Generated by Django 5.1.15 on 2026-09-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('requirement_ambiguity', 'requirement_ambiguity'), ('waiting_analysis', 'waiting_analysis'), ('waiting_client', 'waiting_client'), ('technical', 'technical'), ('environment', 'environment'), ('dependency', 'dependency'), ('management_decision', 'management_decision'), ('other', 'other')], default='other', max_length=40, verbose_name='دسته')),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], default='medium', max_length=20, verbose_name='اهمیت')),
                ('status', models.CharField(choices=[('open', 'open'), ('resolved', 'resolved')], db_index=True, default='open', max_length=20, verbose_name='وضعیت')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رفع')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='teams.member', verbose_name='صاحب مانع')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='projects.project', verbose_name='پروژه')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='work.task', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'مانع',
                'verbose_name_plural': 'موانع',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='blockers_bl_status_eafda7_idx'), models.Index(fields=['project', 'status'], name='blockers_bl_project_a85722_idx')],
            },
        ),
    ]
